package FrontEndToReplicaManager;


/**
* FrontEndToReplicaManager/FrontEndToReplicaManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndToReplicaManager.idl
* Friday, August 4, 2017 3:09:21 o'clock PM EDT
*/

public interface FrontEndToReplicaManagerOperations 
{
  boolean createTRecord (String managerID, String recordID, String firstName, String lastName, String address, String phone, String specialization, String location);
  String getRecordCounts ();
  boolean editRecord (String managerID, String recordID, String fieldName, String newValue);
  boolean createSRecord (String managerID, String recordID, String firstName, String lastName, String coursesRegistered, boolean status, String statusDate);
  boolean transferRecord (String managerID, String recordID, String remoteCenterServerName);
} // interface FrontEndToReplicaManagerOperations
