package FrontEndToReplicaManager;


/**
* FrontEndToReplicaManager/FrontEndToReplicaManager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontendToReplicaManger.idl
* Thursday, August 3, 2017 7:43:38 PM EDT
*/

public interface FrontEndToReplicaManager extends FrontEndToReplicaManagerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FrontEndToReplicaManager
