package FrontEndToReplicaManager;


/**
* FrontEndToReplicaManager/FrontEndToReplicaManager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndToReplicaManager.idl
* Friday, August 4, 2017 3:09:21 o'clock PM EDT
*/

public interface FrontEndToReplicaManager extends FrontEndToReplicaManagerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FrontEndToReplicaManager
