package FrontEndToReplicaManager;

/**
* FrontEndToReplicaManager/FrontEndToReplicaManagerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndToReplicaManager.idl
* Friday, August 4, 2017 3:09:21 o'clock PM EDT
*/

public final class FrontEndToReplicaManagerHolder implements org.omg.CORBA.portable.Streamable
{
  public FrontEndToReplicaManager value = null;

  public FrontEndToReplicaManagerHolder ()
  {
  }

  public FrontEndToReplicaManagerHolder (FrontEndToReplicaManager initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FrontEndToReplicaManagerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FrontEndToReplicaManagerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FrontEndToReplicaManagerHelper.type ();
  }

}
