package FrontEndToReplicaManager;


/**
* FrontEndToReplicaManager/FrontEndToReplicaManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontendToReplicaManger.idl
* Thursday, August 3, 2017 7:43:38 PM EDT
*/

public interface FrontEndToReplicaManagerOperations 
{
  boolean login (String managerID);
  void logout ();
  boolean createTRecord (String managerID, String recordID, String firstName, String lastName, String address, String phone, String specialization, String location);
  String getRecordCounts ();
  boolean editRecord (String managerID, String recordID, String fieldName, String newValue);
  boolean createSRecord (String managerID, String recordID, String firstName, String lastName, String coursesRegistered, boolean status, String statusDate);
  boolean transferRecord (String managerID, String recordID, String remoteCenterServerName);
} // interface FrontEndToReplicaManagerOperations
