package FrontEndToReplicaManager;

/**
* FrontEndToReplicaManager/FrontEndToReplicaManagerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontendToReplicaManger.idl
* Thursday, August 3, 2017 7:43:38 PM EDT
*/

public final class FrontEndToReplicaManagerHolder implements org.omg.CORBA.portable.Streamable
{
  public FrontEndToReplicaManager value = null;

  public FrontEndToReplicaManagerHolder ()
  {
  }

  public FrontEndToReplicaManagerHolder (FrontEndToReplicaManager initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FrontEndToReplicaManagerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FrontEndToReplicaManagerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FrontEndToReplicaManagerHelper.type ();
  }

}
