package CORBAClassManagement;


/**
* CORBAClassManagement/CORBAClassManagement.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBAClassManagement.idl
* Friday, August 4, 2017 1:26:05 o'clock PM EDT
*/

public interface CORBAClassManagement extends CORBAClassManagementOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CORBAClassManagement
