package CORBAClassManagement;


/**
* CORBAClassManagement/CORBAClassManagementOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBAClassManagement.idl
* Sunday, August 6, 2017 11:33:45 o'clock AM EDT
*/

public interface CORBAClassManagementOperations 
{
  boolean createTRecord (String managerID, String firstName, String lastName, String address, String phone, String specialization, String location);
  String getRecordCounts (String managerID);
  boolean editRecord (String managerID, String recordID, String fieldName, String newValue);
  boolean createSRecord (String managerID, String firstName, String lastName, String coursesRegistered, boolean status, String statusDate);
  boolean transferRecord (String managerID, String recordID, String remoteCenterServerName);
} // interface CORBAClassManagementOperations
