package CORBAClassManagement;

/**
* CORBAClassManagement/CORBAClassManagementHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBAClassManagement.idl
* Friday, August 4, 2017 12:06:20 o'clock PM EDT
*/

public final class CORBAClassManagementHolder implements org.omg.CORBA.portable.Streamable
{
  public CORBAClassManagement.CORBAClassManagement value = null;

  public CORBAClassManagementHolder ()
  {
  }

  public CORBAClassManagementHolder (CORBAClassManagement.CORBAClassManagement initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CORBAClassManagement.CORBAClassManagementHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CORBAClassManagement.CORBAClassManagementHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CORBAClassManagement.CORBAClassManagementHelper.type ();
  }

}
