package CORBAClassManagement;

/**
* CORBAClassManagement/CORBAClassManagementHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBAClassManagement.idl
* Sunday, July 30, 2017 11:10:35 o'clock AM EDT
*/

public final class CORBAClassManagementHolder implements org.omg.CORBA.portable.Streamable
{
  public CORBAClassManagement value = null;

  public CORBAClassManagementHolder ()
  {
  }

  public CORBAClassManagementHolder (CORBAClassManagement initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CORBAClassManagementHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CORBAClassManagementHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CORBAClassManagementHelper.type ();
  }

}
