package CORBAClassManagement;


/**
* CORBAClassManagement/CORBAClassManagementHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl
* Thursday, August 3, 2017 7:30:16 PM EDT
*/

abstract public class CORBAClassManagementHelper
{
  private static String  _id = "IDL:CORBAClassManagement/CORBAClassManagement:1.0";

  public static void insert (org.omg.CORBA.Any a, CORBAClassManagement that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CORBAClassManagement extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CORBAClassManagementHelper.id (), "CORBAClassManagement");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CORBAClassManagement read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CORBAClassManagementStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CORBAClassManagement value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CORBAClassManagement narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CORBAClassManagement)
      return (CORBAClassManagement)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _CORBAClassManagementStub stub = new _CORBAClassManagementStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CORBAClassManagement unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CORBAClassManagement)
      return (CORBAClassManagement)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _CORBAClassManagementStub stub = new _CORBAClassManagementStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
