package CORBAClassManagement;

/**
 * CORBAClassManagement/CORBAClassManagementHolder.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from CORBAClassManagement.idl
 * Thursday, August 3, 2017 7:30:16 PM EDT
 */

public final class CORBAClassManagementHolder implements org.omg.CORBA.portable.Streamable {
	public CORBAClassManagement value = null;

	public CORBAClassManagementHolder() {
	}

	public CORBAClassManagementHolder(CORBAClassManagement initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = CORBAClassManagementHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		CORBAClassManagementHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return CORBAClassManagementHelper.type();
	}

}
