package CORBAClassManagement;


/**
* CORBAClassManagement/CORBAClassManagement.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBAClassManagement.idl
* Sunday, July 30, 2017 11:10:35 o'clock AM EDT
*/

public interface CORBAClassManagement extends CORBAClassManagementOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CORBAClassManagement
