module FrontEndToReplicaManager
{
interface FrontEndToReplicaManager{
	 boolean createTRecord(in string managerID,in string recordID, in string firstName, in string lastName, in string address, in string phone, in string specialization, in string location);
	 string getRecordCounts() ;
	 boolean editRecord(in string managerID, in string recordID, in string fieldName, in string newValue);
	 boolean createSRecord(in string managerID,in string recordID, in string firstName, in string lastName, in string coursesRegistered, in boolean status, in string statusDate);
	boolean transferRecord(in string managerID,in string recordID,in string remoteCenterServerName);
	};
};